### ISSUE TITLE
Missing postcondition for routine set_value_from_string_rep from class ACCOUNT_DIGIT

### ISSUE THREAD

**Issue by gamassimino** [nmaguirre/eiffel-bank-ocr#47]
postcondition for ACCOUNT_DIGIT.set_value_from_string_rep is missing

**Comment by gamassimino** [comment]
solved in rev. aabbbba

**Comment by nmaguirre** [comment]
Please notice that your postcondition is wrong. You are comparing the integer-typed field value, with the string-typed parameter new_value. Postcondition will always yield false. Please correct. I'm removing the 'resolved' tag. Thanks!

**Comment by gamassimino** [comment]
solved in rev. 8b84d27

**Comment by nmaguirre** [comment]
Now the postcondition is redundant, since it expresses the same as the invariant. Please remove, and provide a more meaningful postcondition for this routine.. I'm removing the 'resolved' tag, for the moment.

**Comment by gamassimino** [comment]
solved in rev. 89387bd

**Comment by nmaguirre** [comment]
It's still unresolved. As I said, the value, being expanded, will definitely be non-Void, so the postcondition is redundant. I would simply remove the postcondition altogether.

**Comment by gamassimino** [comment]
ok, I deleted the postcondition
solved in rev. 1361656

**Comment by nmaguirre** [comment]
You forgot to tag the issue with 'resolved'. Is it resolved?

**Comment by gamassimino** [comment]
yes, sorry, I forgot the tag

**Comment by nricci** [comment]
This seems to be dealt with. Thanks. I'm closing this issue.
